rm -rf ~/.vscode/extensions
code --install-extension [createInstance] extensionManagementService depends on downloadService which is NOT registered.
code --install-extension adamhartford.vscode-base64
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.numbered-bookmarks
code --install-extension alefragnani.project-manager
code --install-extension berickson324.copyswapper
code --install-extension bibhasdn.unique-lines
code --install-extension codezombiech.gitignore
code --install-extension dbankier.vscode-quick-select
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.find-related
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.code-runner
code --install-extension humao.rest-client
code --install-extension jakeboone02.mediawiki
code --install-extension jhartell.vscode-line-endings
code --install-extension laginha87.short-commands
code --install-extension luggage66.AWK
code --install-extension mechatroner.rainbow-csv
code --install-extension mishkinf.goto-next-previous-member
code --install-extension mkloubert.vscode-remote-workspace
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension ms-vscode.Go
code --install-extension nemesv.copy-file-name
code --install-extension oderwat.indent-rainbow
code --install-extension paulhoughton.vscode-jscpd
code --install-extension ryu1kn.partial-diff
code --install-extension ryu1kn.text-marker
code --install-extension slevesque.vscode-multiclip
code --install-extension steve8708.Align
code --install-extension vscodevim.vim
code --install-extension wmaurer.change-case
code --install-extension xyz.plsql-language
code --install-extension yuna611d.grep2file
code --install-extension ziyasal.vscode-open-in-github
