FOR /D %%p IN ("%USERPROFILE%\.vscode\extensions\*.*") DO rmdir "%%p" /s /q
call code --install-extension [createInstance] extensionManagementService depends on downloadService which is NOT registered.
call code --install-extension adamhartford.vscode-base64
call code --install-extension alefragnani.Bookmarks
call code --install-extension alefragnani.numbered-bookmarks
call code --install-extension alefragnani.project-manager
call code --install-extension berickson324.copyswapper
call code --install-extension bibhasdn.unique-lines
call code --install-extension codezombiech.gitignore
call code --install-extension dbankier.vscode-quick-select
call code --install-extension donjayamanne.git-extension-pack
call code --install-extension donjayamanne.githistory
call code --install-extension DotJoshJohnson.xml
call code --install-extension eamodio.find-related
call code --install-extension eamodio.gitlens
call code --install-extension eg2.tslint
call code --install-extension emmanuelbeziat.vscode-great-icons
call code --install-extension felipecaputo.git-project-manager
call code --install-extension formulahendry.code-runner
call code --install-extension humao.rest-client
call code --install-extension jakeboone02.mediawiki
call code --install-extension jhartell.vscode-line-endings
call code --install-extension laginha87.short-commands
call code --install-extension luggage66.AWK
call code --install-extension mechatroner.rainbow-csv
call code --install-extension mishkinf.goto-next-previous-member
call code --install-extension mkloubert.vscode-remote-workspace
call code --install-extension MS-CEINTL.vscode-language-pack-de
call code --install-extension ms-vscode.Go
call code --install-extension nemesv.copy-file-name
call code --install-extension oderwat.indent-rainbow
call code --install-extension paulhoughton.vscode-jscpd
call code --install-extension ryu1kn.partial-diff
call code --install-extension ryu1kn.text-marker
call code --install-extension slevesque.vscode-multiclip
call code --install-extension steve8708.Align
call code --install-extension vscodevim.vim
call code --install-extension wmaurer.change-case
call code --install-extension xyz.plsql-language
call code --install-extension yuna611d.grep2file
call code --install-extension ziyasal.vscode-open-in-github
