call code --install-extension andyyaldoo.vscode-json
call code --install-extension ban.spellright
call code --install-extension bierner.markdown-preview-github-styles
call code --install-extension ChaunceyKiwi.json-tree-view
call code --install-extension CoenraadS.bracket-pair-colorizer
call code --install-extension Compulim.vscode-clock
call code --install-extension cssho.vscode-svgviewer
call code --install-extension dbaeumer.vscode-eslint
call code --install-extension Ionide.Ionide-fsharp
call code --install-extension k--kato.docomment
call code --install-extension mattn.Lisp
call code --install-extension mauve.terraform
call code --install-extension ms-mssql.mssql
call code --install-extension ms-python.python
call code --install-extension ms-vscode.cpptools
call code --install-extension ms-vscode.csharp
call code --install-extension ms-vscode.vscode-typescript-tslint-plugin
call code --install-extension naumovs.color-highlight
call code --install-extension oderwat.indent-rainbow
call code --install-extension Orta.vscode-jest
call code --install-extension rust-lang.rust
call code --install-extension sdras.night-owl
call code --install-extension Unity.unity-debug
call code --install-extension vscodevim.vim
call code --install-extension waderyan.gitblame
call code --install-extension wayou.vscode-todo-highlight
