call code --install-extension christian-kohler.path-intellisense 
call code --install-extension EditorConfig.EditorConfig 
call code --install-extension eg2.tslint 
call code --install-extension esbenp.prettier-vscode 
call code --install-extension k--kato.docomment 
call code --install-extension Mikael.Angular-BeastCode 
call code --install-extension mrmlnc.vscode-scss 
call code --install-extension ms-vscode.csharp 
call code --install-extension natewallace.angular2-inline 
call code --install-extension rbbit.typescript-hero 
call code --install-extension robertohuertasm.vscode-icons 
call code --install-extension steoates.autoimport 
call code --install-extension wix.vscode-import-cost 
call code --install-extension christian-kohler.path-intellisense 
call code --install-extension EditorConfig.EditorConfig 
call code --install-extension eg2.tslint 
call code --install-extension esbenp.prettier-vscode 
call code --install-extension k--kato.docomment 
call code --install-extension Mikael.Angular-BeastCode 
call code --install-extension mrmlnc.vscode-scss 
call code --install-extension ms-vscode.csharp 
call code --install-extension natewallace.angular2-inline 
call code --install-extension rbbit.typescript-hero 
call code --install-extension robertohuertasm.vscode-icons 
call code --install-extension steoates.autoimport 
call code --install-extension wix.vscode-import-cost 
