code --install-extension auchenberg.vscode-browser-preview
code --install-extension chenng.vscode-translator
code --install-extension cstrap.python-snippets
code --install-extension DeepInThought.vscode-shell-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension frhtylcn.pythonsnippets
code --install-extension g8up.gitee
code --install-extension MaorBarak.pytoipynb
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-zh-hans
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.powershell
code --install-extension RUNNERUP.super-encourager
code --install-extension Shan.code-settings-sync
code --install-extension shaojian.vscode-snippets
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension unbug.codelf
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension voldikss.vscode-ecdict
code --install-extension vscode-icons-team.vscode-icons
code --install-extension XiaodiYan.translator-helper
code --install-extension xuedao.super-translate
